//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sea.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentEnrollDbEntities : DbContext, IDbContext
    {
        public StudentEnrollDbEntities()
            : base("name=StudentEnrollDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassDetail> ClassDetails { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }


        public IDbSet<TEntity> Set<TEntity>() where TEntity : BaseEntity
        {
            return base.Set<TEntity>();
        }

        public DbEntityEntry<T> Entry<T>(T entity) where T : BaseEntity
        {
            return base.Entry(entity);
        }
    }
}
