//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sea.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail :BaseEntity
    {

        public string Surname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<double> GPA { get; set; }
        public Nullable<int> ClassId { get; set; }
    
        public virtual ClassDetail ClassDetail { get; set; }
    }
}
